import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Footer from "./components/Footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-[100dvh] flex-col items-center justify-between relative">
          <UserProvider>
            <AppRouterCacheProvider>
              {children}
              <Footer />
            </AppRouterCacheProvider>
          </UserProvider>
        </main>
      </body>
    </html>
  );
}
