import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-[100dvh] flex-col items-center justify-between relative">
          <AppRouterCacheProvider>
            {children}
            <Footer />
          </AppRouterCacheProvider>
        </main>
      </body>
    </html>
  );
}
